sudo: required
before_install:
  - sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository ppa:bitcoin/bitcoin -y
  - sudo apt-get update
  - sudo apt-get install libdb4.8-dev libdb4.8++-dev
  - sudo apt-get install libboost-all-dev -y
  - find ./ -type f -iname "*.sh" -exec chmod +x {} \;
  - ./autogen.sh
  - ./configure
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc
  
install:
  - make